
// Authentication token (get this from the admin login)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTNlNzVmMDNjNjZhY2M2Y2JiMWUxOGYiLCJyb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluQGV4YW1wbGUuY29tIiwic3RhdHVzIjoidW5sb2NrZWQiLCJpYXQiOjE3NjU3MTg1OTMsImV4cCI6MTc2NTcxOTQ5M30.Rh9PpRjpRxTo2QWSz6FqFE32Zzfg3GX-HpUE2VRLBFo

### Get all users 
GET http://localhost:3000/v1/admin/users
Authorization: Bearer {{token}}
Content-Type: application/json

### Approve a pending store user
PATCH http://localhost:3000/v1/admin/approve/693eb91e5a02e0bcf2bb2251
Authorization: Bearer {{token}}
Content-Type: application/json

### Decline a pending store user
PATCH http://localhost:3000/v1/admin/decline/693d9107e47d8cee4245071a
Authorization: Bearer {{token}}
Content-Type: application/json

### Lock a store user
PATCH http://localhost:3000/v1/admin/user-status/693d912de47d8cee4245071d
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "locked"
}

### Unlock a store user
PATCH http://localhost:3000/v1/admin/user-status/693d912de47d8cee4245071d
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "status": "unlocked"
}

### Delete a store user
DELETE http://localhost:3000/v1/admin/delete/693d912de47d8cee4245071d
Authorization: Bearer {{token}}
Content-Type: application/json

### Create a new admin
POST http://localhost:3000/v1/admin/create-admin
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "username": "Admin22",
  "email": "uusAdmin22@gmail.com",
  "password": "Admin123!"
}

