### Login as Store User (run this first to get token)
# @name storeLogin
POST http://localhost:3000/v1/auth/login
Content-Type: application/json

{
  "username": "KalleKauppias19",
  "password": "Koira123!"
}

###

@token = {{storeLogin.response.body.data.accessToken}}
PUT http://localhost:3000/v1/store
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "K-citymarket Kupittaa",
  "latitude": 30.192059,
  "longitude": 28.945831
}

### Add a product
POST http://localhost:3000/v1/store/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Punainen maito",
  "barcodeType": "EAN",
  "gtin": "1234367893123",
  "price": 3.99,
  "location": {
    "latitudes": 60.169,
    "longitudes": 24.935
  }
}

### Add multiple products at once
POST http://localhost:3000/v1/store/products
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "name": "Makkara",
    "barcodeType": "EAN",
    "gtin": "9376543210486",
    "price": 2.49,
    "location": {
      "latitudes": 60.169,
      "longitudes": 24.935
    }
  },
  {
    "name": "Rasvaton maito",
    "barcodeType": "UPC",
    "gtin": "12324984527891",
    "price": 5.99,
    "location": {
      "latitudes": 60.169,
      "longitudes": 24.935
    }
  }
]

### Apply a discount to a store product
PUT http://localhost:3000/v1/store/products/693ed0416e03525f414c1af7/discount
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "discountedPrice": 1.99
}
