// Authentication token (get this from the store user login)
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2OTNlYjkxZTVhMDJlMGJjZjJiYjIyNTEiLCJyb2xlIjoic3RvcmVVc2VyIiwiZW1haWwiOiJrYWxsZWthdXBwaWFzMTlAZXhhbXBsZS5jb20iLCJzdGF0dXMiOiJ1bmxvY2tlZCIsImlhdCI6MTc2NTcyMzY5NywiZXhwIjoxNzY1NzI0NTk3fQ.7iLf0bgrG3B60FHDTkZld0Ew7WphpwXNh_Gg84u7L90

### Update store name and location
PUT http://localhost:3000/v1/store
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "K-citymarket Kupittaa",
  "latitude": 30.192059,
  "longitude": 25.945831
}

### Add a product
POST http://localhost:3000/v1/store/products
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Kevyt maito",
  "barcodeType": "EAN",
  "gtin": "1234567893123",
  "price": 3.99,
  "location": {
    "latitudes": 60.169,
    "longitudes": 24.935
  }
}

### Add multiple products at once
POST http://localhost:3000/v1/store/products
Authorization: Bearer {{token}}
Content-Type: application/json

[
  {
    "name": "Makkara",
    "barcodeType": "EAN",
    "gtin": "9376543210486",
    "price": 2.49,
    "location": {
      "latitudes": 60.169,
      "longitudes": 24.935
    }
  },
  {
    "name": "Rasvaton maito",
    "barcodeType": "UPC",
    "gtin": "12324984527891",
    "price": 5.99,
    "location": {
      "latitudes": 60.169,
      "longitudes": 24.935
    }
  }
]

### Apply a discount to a store product
PUT http://localhost:3000/v1/store/products/693ed0416e03525f414c1af7/discount
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "discountedPrice": 1.99
}
